/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.umgc.vehiclesofinterestdesktop;

import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author viet
 */
public class MainScreen extends javax.swing.JFrame {
    
    VehiclesOfInterestController voiControl = new VehiclesOfInterestController();
    String PLATE_PLACEHOLDER = "Enter License Plate";
    String MAKE_PLACEHOLDER = "Enter Make";
    String MODEL_PLACEHOLDER = "Enter Model";
    String REASON_PLACEHOLDER = "Enter Reason";
    String DESCRIPTION_PLACEHOLDER = "Enter Description";
    String YEAR_PLACEHOLDER = "Enter Year";
    String COLOR_PLACEHOLDER = "Enter Color";
    String OWNER_NAME_PLACEHOLDER = "Enter Owner's Name";
    String OWNER_PHONE_PLACEHOLDER = "Enter Owner's Phone";

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        VehiclesOfInterestPane = new javax.swing.JPanel();
        ShowVehiclesOfInterestButton = new javax.swing.JButton();
        VehiclesOfInterestSearchText = new javax.swing.JTextField();
        VehiclesOfInterestLicenseSearchButton = new javax.swing.JButton();
        NewVehicleOfInterestPlateText = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        NewVehicleOfInterestReasonText = new javax.swing.JFormattedTextField();
        NewVehicleOfInterestMakeText = new javax.swing.JFormattedTextField();
        NewVehicleOfInterestModelText = new javax.swing.JFormattedTextField();
        NewVehicleOfInterestYearText = new javax.swing.JFormattedTextField();
        NewVehicleOfInterestColorText = new javax.swing.JFormattedTextField();
        NewVehicleOfInterestOwnerNameText = new javax.swing.JFormattedTextField();
        NewVehicleOfInterestOwnerPhoneText = new javax.swing.JFormattedTextField();
        AddVehicleOfInterestButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RemoveVehicleOfInterestButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ReasonsForInterestPane = new javax.swing.JPanel();
        ShowReasonsForInterestButton = new javax.swing.JButton();
        ReasonForInterestText = new javax.swing.JTextField();
        AddReasonForInterestButton = new javax.swing.JButton();
        RemoveReasonForInterestButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        ReasonForInterestDescriptionText = new javax.swing.JTextField();
        VehicleModelsPane = new javax.swing.JPanel();
        ShowVehicleModelsButton = new javax.swing.JButton();
        NewMakeText = new javax.swing.JTextField();
        AddNewMakeButton = new javax.swing.JButton();
        NewModelText = new javax.swing.JTextField();
        AddNewModelButton = new javax.swing.JButton();
        RemoveMakeButton = new javax.swing.JButton();
        RemoveModelButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        VehiclesOfInterestPane.setBackground(new java.awt.Color(255, 255, 255));

        ShowVehiclesOfInterestButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        ShowVehiclesOfInterestButton.setText("Show Vehicles of Interest");
        ShowVehiclesOfInterestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowVehiclesOfInterestButtonActionPerformed(evt);
            }
        });

        VehiclesOfInterestSearchText.setForeground(new java.awt.Color(102, 102, 102));
        VehiclesOfInterestSearchText.setText("Enter License Plate"); // NOI18N
        VehiclesOfInterestSearchText.setMinimumSize(new java.awt.Dimension(200, 23));
        VehiclesOfInterestSearchText.setPreferredSize(new java.awt.Dimension(200, 23));
        VehiclesOfInterestSearchText.setSize(new java.awt.Dimension(200, 23));
        VehiclesOfInterestSearchText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                VehiclesOfInterestSearchTextFocusLost(evt);
            }
        });
        VehiclesOfInterestSearchText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VehiclesOfInterestSearchTextMouseClicked(evt);
            }
        });

        VehiclesOfInterestLicenseSearchButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        VehiclesOfInterestLicenseSearchButton.setText("Search");
        VehiclesOfInterestLicenseSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehiclesOfInterestLicenseSearchButtonActionPerformed(evt);
            }
        });

        NewVehicleOfInterestPlateText.setForeground(new java.awt.Color(102, 102, 102));
        NewVehicleOfInterestPlateText.setText("Enter License Plate");
        NewVehicleOfInterestPlateText.setMinimumSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestPlateText.setPreferredSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestPlateText.setSize(new java.awt.Dimension(200, 23));
        NewVehicleOfInterestPlateText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewVehicleOfInterestPlateTextFocusLost(evt);
            }
        });
        NewVehicleOfInterestPlateText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewVehicleOfInterestPlateTextMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Add New Vehicle of Interest");

        NewVehicleOfInterestReasonText.setForeground(new java.awt.Color(102, 102, 102));
        NewVehicleOfInterestReasonText.setText("Enter Reason");
        NewVehicleOfInterestReasonText.setMinimumSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestReasonText.setPreferredSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestReasonText.setSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestReasonText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewVehicleOfInterestReasonTextFocusLost(evt);
            }
        });
        NewVehicleOfInterestReasonText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewVehicleOfInterestReasonTextMouseClicked(evt);
            }
        });

        NewVehicleOfInterestMakeText.setForeground(new java.awt.Color(102, 102, 102));
        NewVehicleOfInterestMakeText.setText("Enter Make");
        NewVehicleOfInterestMakeText.setMinimumSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestMakeText.setPreferredSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestMakeText.setSize(new java.awt.Dimension(200, 23));
        NewVehicleOfInterestMakeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewVehicleOfInterestMakeTextFocusLost(evt);
            }
        });
        NewVehicleOfInterestMakeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewVehicleOfInterestMakeTextMouseClicked(evt);
            }
        });

        NewVehicleOfInterestModelText.setForeground(new java.awt.Color(102, 102, 102));
        NewVehicleOfInterestModelText.setText("Enter Model");
        NewVehicleOfInterestModelText.setMinimumSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestModelText.setPreferredSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestModelText.setSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestModelText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewVehicleOfInterestModelTextFocusLost(evt);
            }
        });
        NewVehicleOfInterestModelText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewVehicleOfInterestModelTextMouseClicked(evt);
            }
        });

        NewVehicleOfInterestYearText.setForeground(new java.awt.Color(102, 102, 102));
        NewVehicleOfInterestYearText.setText("Enter Year");
        NewVehicleOfInterestYearText.setMinimumSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestYearText.setPreferredSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestYearText.setSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestYearText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewVehicleOfInterestYearTextFocusLost(evt);
            }
        });
        NewVehicleOfInterestYearText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewVehicleOfInterestYearTextMouseClicked(evt);
            }
        });

        NewVehicleOfInterestColorText.setForeground(new java.awt.Color(102, 102, 102));
        NewVehicleOfInterestColorText.setText("Enter Color");
        NewVehicleOfInterestColorText.setMinimumSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestColorText.setPreferredSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestColorText.setSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestColorText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewVehicleOfInterestColorTextFocusLost(evt);
            }
        });
        NewVehicleOfInterestColorText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewVehicleOfInterestColorTextMouseClicked(evt);
            }
        });

        NewVehicleOfInterestOwnerNameText.setForeground(new java.awt.Color(102, 102, 102));
        NewVehicleOfInterestOwnerNameText.setText("Enter Owner's Name");
        NewVehicleOfInterestOwnerNameText.setMinimumSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestOwnerNameText.setPreferredSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestOwnerNameText.setSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestOwnerNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewVehicleOfInterestOwnerNameTextFocusLost(evt);
            }
        });
        NewVehicleOfInterestOwnerNameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewVehicleOfInterestOwnerNameTextMouseClicked(evt);
            }
        });

        NewVehicleOfInterestOwnerPhoneText.setForeground(new java.awt.Color(102, 102, 102));
        NewVehicleOfInterestOwnerPhoneText.setText("Enter Owner's Phone");
        NewVehicleOfInterestOwnerPhoneText.setMinimumSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestOwnerPhoneText.setPreferredSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestOwnerPhoneText.setSize(new java.awt.Dimension(150, 23));
        NewVehicleOfInterestOwnerPhoneText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewVehicleOfInterestOwnerPhoneTextFocusLost(evt);
            }
        });
        NewVehicleOfInterestOwnerPhoneText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewVehicleOfInterestOwnerPhoneTextMouseClicked(evt);
            }
        });

        AddVehicleOfInterestButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        AddVehicleOfInterestButton.setText("Add / Update");
        AddVehicleOfInterestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVehicleOfInterestButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Required Fields");

        jLabel4.setText("Optional Fields");

        RemoveVehicleOfInterestButton.setForeground(new java.awt.Color(255, 51, 0));
        RemoveVehicleOfInterestButton.setText("Remove");
        RemoveVehicleOfInterestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveVehicleOfInterestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VehiclesOfInterestPaneLayout = new javax.swing.GroupLayout(VehiclesOfInterestPane);
        VehiclesOfInterestPane.setLayout(VehiclesOfInterestPaneLayout);
        VehiclesOfInterestPaneLayout.setHorizontalGroup(
            VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiclesOfInterestPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehiclesOfInterestPaneLayout.createSequentialGroup()
                        .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(ShowVehiclesOfInterestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclesOfInterestPaneLayout.createSequentialGroup()
                                .addComponent(VehiclesOfInterestSearchText, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(VehiclesOfInterestLicenseSearchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveVehicleOfInterestButton)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclesOfInterestPaneLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewVehicleOfInterestMakeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewVehicleOfInterestPlateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewVehicleOfInterestYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewVehicleOfInterestOwnerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NewVehicleOfInterestColorText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NewVehicleOfInterestOwnerPhoneText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NewVehicleOfInterestReasonText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewVehicleOfInterestModelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
            .addGroup(VehiclesOfInterestPaneLayout.createSequentialGroup()
                .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehiclesOfInterestPaneLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel3))
                    .addGroup(VehiclesOfInterestPaneLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(VehiclesOfInterestPaneLayout.createSequentialGroup()
                .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehiclesOfInterestPaneLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel4))
                    .addGroup(VehiclesOfInterestPaneLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(AddVehicleOfInterestButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VehiclesOfInterestPaneLayout.setVerticalGroup(
            VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiclesOfInterestPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehiclesOfInterestSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehiclesOfInterestLicenseSearchButton)
                    .addComponent(RemoveVehicleOfInterestButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowVehiclesOfInterestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewVehicleOfInterestPlateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewVehicleOfInterestReasonText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewVehicleOfInterestMakeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewVehicleOfInterestModelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewVehicleOfInterestYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewVehicleOfInterestColorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehiclesOfInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewVehicleOfInterestOwnerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewVehicleOfInterestOwnerPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddVehicleOfInterestButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Vehicles of Interest", VehiclesOfInterestPane);

        ReasonsForInterestPane.setBackground(new java.awt.Color(255, 255, 255));

        ShowReasonsForInterestButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        ShowReasonsForInterestButton.setText("Show Reasons for Interest");
        ShowReasonsForInterestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowReasonsForInterestButtonActionPerformed(evt);
            }
        });

        ReasonForInterestText.setForeground(new java.awt.Color(102, 102, 102));
        ReasonForInterestText.setText("Enter Reason");
        ReasonForInterestText.setMinimumSize(new java.awt.Dimension(200, 23));
        ReasonForInterestText.setPreferredSize(new java.awt.Dimension(200, 23));
        ReasonForInterestText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ReasonForInterestTextFocusLost(evt);
            }
        });
        ReasonForInterestText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReasonForInterestTextMouseClicked(evt);
            }
        });

        AddReasonForInterestButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        AddReasonForInterestButton.setText("Add / Update");
        AddReasonForInterestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddReasonForInterestButtonActionPerformed(evt);
            }
        });

        RemoveReasonForInterestButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        RemoveReasonForInterestButton.setText("Remove");
        RemoveReasonForInterestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveReasonForInterestButtonActionPerformed(evt);
            }
        });

        ReasonForInterestDescriptionText.setForeground(new java.awt.Color(102, 102, 102));
        ReasonForInterestDescriptionText.setText("Enter Description");
        ReasonForInterestDescriptionText.setMinimumSize(new java.awt.Dimension(200, 23));
        ReasonForInterestDescriptionText.setPreferredSize(new java.awt.Dimension(200, 23));
        ReasonForInterestDescriptionText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ReasonForInterestDescriptionTextFocusLost(evt);
            }
        });
        ReasonForInterestDescriptionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReasonForInterestDescriptionTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ReasonsForInterestPaneLayout = new javax.swing.GroupLayout(ReasonsForInterestPane);
        ReasonsForInterestPane.setLayout(ReasonsForInterestPaneLayout);
        ReasonsForInterestPaneLayout.setHorizontalGroup(
            ReasonsForInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReasonsForInterestPaneLayout.createSequentialGroup()
                .addGroup(ReasonsForInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ReasonsForInterestPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ReasonsForInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShowReasonsForInterestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ReasonsForInterestPaneLayout.createSequentialGroup()
                                .addGroup(ReasonsForInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ReasonsForInterestPaneLayout.createSequentialGroup()
                                        .addComponent(ReasonForInterestDescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(AddReasonForInterestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(ReasonsForInterestPaneLayout.createSequentialGroup()
                                        .addComponent(ReasonForInterestText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RemoveReasonForInterestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 86, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        ReasonsForInterestPaneLayout.setVerticalGroup(
            ReasonsForInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReasonsForInterestPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShowReasonsForInterestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReasonsForInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveReasonForInterestButton)
                    .addComponent(ReasonForInterestText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReasonsForInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddReasonForInterestButton)
                    .addComponent(ReasonForInterestDescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Reasons for Interest", ReasonsForInterestPane);

        VehicleModelsPane.setBackground(new java.awt.Color(255, 255, 255));
        VehicleModelsPane.setForeground(new java.awt.Color(102, 102, 102));

        ShowVehicleModelsButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        ShowVehicleModelsButton.setText("Show Vehicle Models");
        ShowVehicleModelsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowVehicleModelsButtonActionPerformed(evt);
            }
        });

        NewMakeText.setForeground(new java.awt.Color(102, 102, 102));
        NewMakeText.setText("Enter Make");
        NewMakeText.setMinimumSize(new java.awt.Dimension(100, 23));
        NewMakeText.setPreferredSize(new java.awt.Dimension(100, 23));
        NewMakeText.setSize(new java.awt.Dimension(100, 23));
        NewMakeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewMakeTextFocusLost(evt);
            }
        });
        NewMakeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewMakeTextMouseClicked(evt);
            }
        });

        AddNewMakeButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        AddNewMakeButton.setText("Add");
        AddNewMakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewMakeButtonActionPerformed(evt);
            }
        });

        NewModelText.setForeground(new java.awt.Color(102, 102, 102));
        NewModelText.setText("Enter Model");
        NewModelText.setMinimumSize(new java.awt.Dimension(100, 23));
        NewModelText.setPreferredSize(new java.awt.Dimension(100, 23));
        NewModelText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewModelTextFocusLost(evt);
            }
        });
        NewModelText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewModelTextMouseClicked(evt);
            }
        });

        AddNewModelButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        AddNewModelButton.setText("Add");
        AddNewModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewModelButtonActionPerformed(evt);
            }
        });

        RemoveMakeButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        RemoveMakeButton.setText("Remove");
        RemoveMakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMakeButtonActionPerformed(evt);
            }
        });

        RemoveModelButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        RemoveModelButton.setText("Remove");
        RemoveModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveModelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VehicleModelsPaneLayout = new javax.swing.GroupLayout(VehicleModelsPane);
        VehicleModelsPane.setLayout(VehicleModelsPaneLayout);
        VehicleModelsPaneLayout.setHorizontalGroup(
            VehicleModelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleModelsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VehicleModelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowVehicleModelsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addGroup(VehicleModelsPaneLayout.createSequentialGroup()
                        .addGroup(VehicleModelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NewModelText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(NewMakeText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VehicleModelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VehicleModelsPaneLayout.createSequentialGroup()
                                .addComponent(AddNewModelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveModelButton))
                            .addGroup(VehicleModelsPaneLayout.createSequentialGroup()
                                .addComponent(AddNewMakeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveMakeButton)))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        VehicleModelsPaneLayout.setVerticalGroup(
            VehicleModelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleModelsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShowVehicleModelsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehicleModelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewMakeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveMakeButton)
                    .addComponent(AddNewMakeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehicleModelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewModelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNewModelButton)
                    .addComponent(RemoveModelButton))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Vehicle Models", VehicleModelsPane);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Maryland State Police Headquarters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TabbedPane))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowReasonsForInterestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowReasonsForInterestButtonActionPerformed
        String[] cols = {"Reason", "Descrition"};
        String[][] rows = voiControl.getAllReasonsForInterest();
        JTable table = new JTable(rows, cols);
        
        String title = "All Reasons for Interest";
        showTable(table, title, 800, 300);
    }//GEN-LAST:event_ShowReasonsForInterestButtonActionPerformed

    private void ShowVehicleModelsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowVehicleModelsButtonActionPerformed
        String[] cols = {"Model", "Make"};
        String[][] rows = voiControl.allVehicleModel();
        JTable table = new JTable(rows, cols); 
        
        String title = "All Vehicle Models";
        showTable(table, title, 500, 500);
    }//GEN-LAST:event_ShowVehicleModelsButtonActionPerformed

    private void AddNewMakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewMakeButtonActionPerformed
        String newMake = NewMakeText.getText().trim();
        if (!newMake.isEmpty() && !newMake.equals(MAKE_PLACEHOLDER)) {
            voiControl.createVehicleMake(newMake);
            
            String message = newMake + " added!";
            alert("Success", message, 300, 100);
        }
    }//GEN-LAST:event_AddNewMakeButtonActionPerformed

    private void NewMakeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMakeTextMouseClicked
        NewMakeText.setText("");
    }//GEN-LAST:event_NewMakeTextMouseClicked

    private void NewModelTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewModelTextMouseClicked
        NewModelText.setText("");
    }//GEN-LAST:event_NewModelTextMouseClicked

    private void AddNewModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewModelButtonActionPerformed
        String newMake = NewMakeText.getText().trim();
        String newModel = NewModelText.getText().trim();
        
        if (newMake.isEmpty() || newMake.equals(MAKE_PLACEHOLDER) 
                || newModel.isEmpty() || newModel.equals(MODEL_PLACEHOLDER)) {
            String message = "Both Model and Make are required!";
            alert("Warning", message, 300, 100);
        }
        
        if (!newMake.isEmpty() && !newModel.isEmpty()) {
            if (isFound(newMake, "make") && isFound(newModel, "model")) {
                String message = newMake + " " + newModel + " already exists.";
                alert("Notice", message, 300, 100);
                return;
            }
            
            // If the new make doesn't exist, add it to the table
            if (!isFound(newMake, "make")) {
                voiControl.createVehicleMake(newMake);
            }
            voiControl.createVechileModel(newModel, newMake);
            
            String message = newMake + " " + newModel + " added!";
            alert("Success", message, 300, 100);
        }
    }//GEN-LAST:event_AddNewModelButtonActionPerformed

    private void RemoveMakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveMakeButtonActionPerformed
        String enteredMake = NewMakeText.getText().trim();
        
        if (!isFound(enteredMake, "make")) {
            String message = "Make: " + enteredMake + " not found!";
            alert("Warning", message, 300, 100);
            return;
        }
        
        try {
            voiControl.deleteVehicleMake(enteredMake);
            String message = "Make: " + enteredMake + " removed.";
            alert("Success", message, 300, 100);
        } catch(Exception e) {
            String message = "Make: " + enteredMake + " cannot be removed."
                    + " Reason: " + e.getMessage();
            alert("Warning", message, 800, 100);
        }
    }//GEN-LAST:event_RemoveMakeButtonActionPerformed

    private void RemoveModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveModelButtonActionPerformed
        String enteredModel = NewModelText.getText().trim();
        
        if (!isFound(enteredModel, "model")) {
            String message = "Model: " + enteredModel + " not found!";
            alert("Warning", message, 300, 100);
            return;
        }
        
        try {
            voiControl.deleteVehicleModel(enteredModel);
            String message = "Model: " + enteredModel + " removed.";
            alert("Success", message, 300, 100);
        } catch(Exception e) {
            String message = "Model: " + enteredModel + " cannot be removed."
                    + " Reason: " + e.getMessage();
            alert("Warning", message, 800, 100);
        }
    }//GEN-LAST:event_RemoveModelButtonActionPerformed

    private void AddReasonForInterestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddReasonForInterestButtonActionPerformed
        String reason = ReasonForInterestText.getText().trim();
        String description = ReasonForInterestDescriptionText.getText().trim();
        
        if (reason.isEmpty() || reason.equals(REASON_PLACEHOLDER)
                || description.isEmpty() 
                || description.equals(DESCRIPTION_PLACEHOLDER)) {
            String message = "Both Reason and Description are required!";
            alert("Warning", message, 300, 100);
            return;
        }
        
        if (isFound(reason, "reason")) {
            voiControl.updateReasonForInterest(reason, description);
            String message = "Reason for interest: " + reason + " exists."
                    + " Description updated.";
            alert("Notice", message, 800, 100);
            return;
        }
        
        try {
            voiControl.createReasonOfInterest(reason, description);
            String message = "Reason for interest: " + reason + " added.";
            alert("Success", message, 800, 100);
        } catch(Exception e) {
            String message = "Reason for interest: " + reason + " cannot be added."
                    + " Reason: " + e.getMessage();
            alert("Warning", message, 800, 100);
        }
    }//GEN-LAST:event_AddReasonForInterestButtonActionPerformed

    private void RemoveReasonForInterestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveReasonForInterestButtonActionPerformed
        String enteredReason = ReasonForInterestText.getText().trim();
        
        if (!isFound(enteredReason, "reason")) {
            String message = "Reason for interest: " + enteredReason + " not found!";
            alert("Warning", message, 300, 100);
            return;
        }
        
        try {
            voiControl.deleteReasonForInterestBreed(enteredReason);
            String message = "Reason: " + enteredReason + " removed.";
            alert("Success", message, 300, 100);
        } catch(Exception e) {
            String message = "Reason for interest: " + enteredReason 
                    + " cannot be removed."
                    + " Reason: " + e.getMessage();
            alert("Warning", message, 800, 100);
        }
    }//GEN-LAST:event_RemoveReasonForInterestButtonActionPerformed

    private void ReasonForInterestTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReasonForInterestTextMouseClicked
        ReasonForInterestText.setText("");
    }//GEN-LAST:event_ReasonForInterestTextMouseClicked

    private void RemoveVehicleOfInterestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveVehicleOfInterestButtonActionPerformed
        String plate = VehiclesOfInterestSearchText.getText().trim();
        if (plate.isEmpty() || plate.equals(PLATE_PLACEHOLDER)) return;
        
        if (!isFound(plate, "wanted")) {
            String message = "The vehicle: " + plate + " is not wanted.";
            alert("Notice", message, 300, 100);
            return;
        }
        
        try {
            voiControl.deleteVehicleOfInterest(plate);
            String message = "Vehicle: " + plate + " removed from Vehicles of Interest.";
            alert("Success", message, 300, 100);
        } catch(Exception e) {
            String message = "Vehicle: " + plate 
                    + " cannot be removed."
                    + " Reason: " + e.getMessage();
            alert("Warning", message, 800, 100);
        }
    }//GEN-LAST:event_RemoveVehicleOfInterestButtonActionPerformed

    private void AddVehicleOfInterestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVehicleOfInterestButtonActionPerformed
        // Required fields
        String plate = NewVehicleOfInterestPlateText.getText().trim();
        String reason = NewVehicleOfInterestReasonText.getText().trim();
        String make = NewVehicleOfInterestMakeText.getText().trim();
        String model = NewVehicleOfInterestModelText.getText().trim();
        
        if (plate.isEmpty() || reason.isEmpty() || make.isEmpty() || model.isEmpty()
                || plate.equals(PLATE_PLACEHOLDER) || reason.equals(REASON_PLACEHOLDER)
                || make.equals(MAKE_PLACEHOLDER) || model.equals(MODEL_PLACEHOLDER)) {
            String message = "All required fields must be filled!";
            alert("Warning", message, 300, 100);
            return;
        }
        
        // Optional fields
        String year = NewVehicleOfInterestYearText.getText().trim();
        String color = NewVehicleOfInterestColorText.getText().trim();
        String ownerName = NewVehicleOfInterestOwnerNameText.getText().trim();
        String ownerPhone = NewVehicleOfInterestOwnerPhoneText.getText().trim();
        
        if (year.equals(YEAR_PLACEHOLDER)) {
            year = "";
        }
        
        if (color.equals(COLOR_PLACEHOLDER)) {
            color = "";
        }
        
        if (ownerName.equals(OWNER_NAME_PLACEHOLDER)) {
            ownerName = "";
        }
        
        if (ownerPhone.equals(OWNER_PHONE_PLACEHOLDER)) {
            ownerPhone = "";
        }
        
        try {
            if (!isFound(make, "make")) {
                voiControl.createVehicleMake(make);
            }
            
            if (!isFound(model, "model")) {
                voiControl.createVechileModel(model, make);
            }
            
            if (!isFound(reason, "reason")) {
                voiControl.createReasonOfInterest(reason, "N/A");
            }
            
            if (isFound(plate, "wanted")) {
                voiControl.updateVehicleOfInterest(plate, reason, make, model, 
                        year, color, ownerName, ownerPhone);
                String message = "Vehicle: " + plate + " already of interest."
                    + " Details updated.";
                alert("Notice", message, 800, 100);
                return;
            }
            
            voiControl.createVehicleOfInterest(plate, reason, make, model, year, 
                    color, ownerName, ownerPhone);
            
            String message = "Vehicle: " + plate + " added.";
            alert("Success", message, 300, 100);
        } catch(Exception e) {
            String message = "Vehicle: " + plate 
                    + " cannot be added."
                    + " Reason: " + e.getMessage();
            alert("Warning", message, 800, 100);
        }
    }//GEN-LAST:event_AddVehicleOfInterestButtonActionPerformed

    private void VehiclesOfInterestLicenseSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehiclesOfInterestLicenseSearchButtonActionPerformed
        String plate = VehiclesOfInterestSearchText.getText().trim();
        if (plate.isEmpty() || plate.equals(PLATE_PLACEHOLDER)) return;

        if (!isFound(plate, "wanted")) {
            String message = "The vehicle: " + plate + " is not wanted.";
            alert("Notice", message, 300, 100);
            return;
        }

        String[] cols = {"License Plate", "Reason", "Make", "Model", "Year", 
            "Color", "Owners Name", "Owner Phone"};
        String[] details = voiControl.getVehicleOfInterestByLicense(plate);
        String[][] rows = new String[2][8];
        rows[0] = details;
        JTable table = new JTable(rows, cols);

        String title = "Details of Vehicle with License Plate: " + plate;
        showTable(table, title, 800, 100);
    }//GEN-LAST:event_VehiclesOfInterestLicenseSearchButtonActionPerformed

    private void VehiclesOfInterestSearchTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehiclesOfInterestSearchTextMouseClicked
        VehiclesOfInterestSearchText.setText("");
    }//GEN-LAST:event_VehiclesOfInterestSearchTextMouseClicked

    private void ShowVehiclesOfInterestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowVehiclesOfInterestButtonActionPerformed
        String[] cols = {"License Plate", "Reason", "Make", "Model", "Year", "Color", "Owners Name", "Owners_phone"};
        String[][] rows = voiControl.allVehicleOfInterest();
        JTable table = new JTable(rows, cols);

        String title = "All Vehicles of Interest";
        showTable(table, title, 800, 500);
    }//GEN-LAST:event_ShowVehiclesOfInterestButtonActionPerformed

    private void ReasonForInterestDescriptionTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReasonForInterestDescriptionTextMouseClicked
        ReasonForInterestDescriptionText.setText("");
    }//GEN-LAST:event_ReasonForInterestDescriptionTextMouseClicked

    private void NewVehicleOfInterestPlateTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestPlateTextMouseClicked
        NewVehicleOfInterestPlateText.setText("");
    }//GEN-LAST:event_NewVehicleOfInterestPlateTextMouseClicked

    private void NewVehicleOfInterestReasonTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestReasonTextMouseClicked
        NewVehicleOfInterestReasonText.setText("");
    }//GEN-LAST:event_NewVehicleOfInterestReasonTextMouseClicked

    private void NewVehicleOfInterestMakeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestMakeTextMouseClicked
        NewVehicleOfInterestMakeText.setText("");
    }//GEN-LAST:event_NewVehicleOfInterestMakeTextMouseClicked

    private void NewVehicleOfInterestModelTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestModelTextMouseClicked
        NewVehicleOfInterestModelText.setText("");
    }//GEN-LAST:event_NewVehicleOfInterestModelTextMouseClicked

    private void NewVehicleOfInterestYearTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestYearTextMouseClicked
        NewVehicleOfInterestYearText.setText("");
    }//GEN-LAST:event_NewVehicleOfInterestYearTextMouseClicked

    private void NewVehicleOfInterestColorTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestColorTextMouseClicked
        NewVehicleOfInterestColorText.setText("");
    }//GEN-LAST:event_NewVehicleOfInterestColorTextMouseClicked

    private void NewVehicleOfInterestOwnerNameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestOwnerNameTextMouseClicked
        NewVehicleOfInterestOwnerNameText.setText("");
    }//GEN-LAST:event_NewVehicleOfInterestOwnerNameTextMouseClicked

    private void NewVehicleOfInterestOwnerPhoneTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestOwnerPhoneTextMouseClicked
        NewVehicleOfInterestOwnerPhoneText.setText("");
    }//GEN-LAST:event_NewVehicleOfInterestOwnerPhoneTextMouseClicked

    private void VehiclesOfInterestSearchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VehiclesOfInterestSearchTextFocusLost
        if (VehiclesOfInterestSearchText.getText().isEmpty()) {
            VehiclesOfInterestSearchText.setText(PLATE_PLACEHOLDER);
        }
    }//GEN-LAST:event_VehiclesOfInterestSearchTextFocusLost

    private void NewVehicleOfInterestPlateTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestPlateTextFocusLost
        if (NewVehicleOfInterestPlateText.getText().isEmpty()) {
            NewVehicleOfInterestPlateText.setText(PLATE_PLACEHOLDER);
        }
    }//GEN-LAST:event_NewVehicleOfInterestPlateTextFocusLost

    private void NewVehicleOfInterestReasonTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestReasonTextFocusLost
        if (NewVehicleOfInterestReasonText.getText().isEmpty()) {
            NewVehicleOfInterestReasonText.setText(REASON_PLACEHOLDER);
        }
    }//GEN-LAST:event_NewVehicleOfInterestReasonTextFocusLost

    private void NewVehicleOfInterestMakeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestMakeTextFocusLost
        if (NewVehicleOfInterestMakeText.getText().isEmpty()) {
            NewVehicleOfInterestMakeText.setText(MAKE_PLACEHOLDER);
        }
    }//GEN-LAST:event_NewVehicleOfInterestMakeTextFocusLost

    private void NewVehicleOfInterestModelTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestModelTextFocusLost
        if (NewVehicleOfInterestModelText.getText().isEmpty()) {
            NewVehicleOfInterestModelText.setText(MODEL_PLACEHOLDER);
        }
    }//GEN-LAST:event_NewVehicleOfInterestModelTextFocusLost

    private void NewVehicleOfInterestYearTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestYearTextFocusLost
        if (NewVehicleOfInterestYearText.getText().isEmpty()) {
            NewVehicleOfInterestYearText.setText(YEAR_PLACEHOLDER);
        }
    }//GEN-LAST:event_NewVehicleOfInterestYearTextFocusLost

    private void NewVehicleOfInterestColorTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestColorTextFocusLost
        if (NewVehicleOfInterestColorText.getText().isEmpty()) {
            NewVehicleOfInterestColorText.setText(COLOR_PLACEHOLDER);
        }
    }//GEN-LAST:event_NewVehicleOfInterestColorTextFocusLost

    private void NewVehicleOfInterestOwnerNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestOwnerNameTextFocusLost
        if (NewVehicleOfInterestOwnerNameText.getText().isEmpty()) {
            NewVehicleOfInterestOwnerNameText.setText(OWNER_NAME_PLACEHOLDER);
        }
    }//GEN-LAST:event_NewVehicleOfInterestOwnerNameTextFocusLost

    private void NewVehicleOfInterestOwnerPhoneTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewVehicleOfInterestOwnerPhoneTextFocusLost
        if (NewVehicleOfInterestOwnerPhoneText.getText().isEmpty()) {
            NewVehicleOfInterestOwnerPhoneText.setText(OWNER_PHONE_PLACEHOLDER);
        }
    }//GEN-LAST:event_NewVehicleOfInterestOwnerPhoneTextFocusLost

    private void ReasonForInterestTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ReasonForInterestTextFocusLost
        if (ReasonForInterestText.getText().isEmpty()) {
            ReasonForInterestText.setText(REASON_PLACEHOLDER);
        }
    }//GEN-LAST:event_ReasonForInterestTextFocusLost

    private void ReasonForInterestDescriptionTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ReasonForInterestDescriptionTextFocusLost
        if (ReasonForInterestDescriptionText.getText().isEmpty()) {
            ReasonForInterestDescriptionText.setText(DESCRIPTION_PLACEHOLDER);
        }
    }//GEN-LAST:event_ReasonForInterestDescriptionTextFocusLost

    private void NewMakeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewMakeTextFocusLost
        if (NewMakeText.getText().isEmpty()) {
            NewMakeText.setText(MAKE_PLACEHOLDER);
        }
    }//GEN-LAST:event_NewMakeTextFocusLost

    private void NewModelTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewModelTextFocusLost
        if (NewModelText.getText().isEmpty()) {
            NewModelText.setText(MODEL_PLACEHOLDER);
        }
    }//GEN-LAST:event_NewModelTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }
    
    private void showTable(JTable table, String title, int width, int height) {
        JFrame frame = new JFrame();
        frame.setTitle(title);
        frame.add(new JScrollPane(table));
        frame.setSize(width, height);
        frame.setVisible(true);
    }
    
    private void alert(String title, String message, 
            int width, int height) {
        JFrame frame = new JFrame();
        frame.setTitle(title);
        frame.add(new JLabel(message));
        frame.setSize(width, height);
        frame.setVisible(true);
    }
    
    private boolean isFound(String field, String fieldType) {
        switch (fieldType) {
            case "make": 
                String[] allMakes = voiControl.allVehicleMakeKey();
                if (Arrays.asList(allMakes).contains(field)) {
                    return true;
                }
                return false;
            case "model":
                String[] allModels = voiControl.allVehicleModelKey();
                if (Arrays.asList(allModels).contains(field)) {
                    return true;
                }
                return false;
            case "reason":
                String[] allReasons = voiControl.allReasonsForInterestKey();
                if (Arrays.asList(allReasons).contains(field)) {
                    return true;
                }
                return false;
            case "wanted":
                String[] allWantedPlates = voiControl.allVehicleOfInterestKey();
                if (Arrays.asList(allWantedPlates).contains(field)) {
                    return true;
                }
                return false;
            default: return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewMakeButton;
    private javax.swing.JButton AddNewModelButton;
    private javax.swing.JButton AddReasonForInterestButton;
    private javax.swing.JButton AddVehicleOfInterestButton;
    private javax.swing.JTextField NewMakeText;
    private javax.swing.JTextField NewModelText;
    private javax.swing.JFormattedTextField NewVehicleOfInterestColorText;
    private javax.swing.JFormattedTextField NewVehicleOfInterestMakeText;
    private javax.swing.JFormattedTextField NewVehicleOfInterestModelText;
    private javax.swing.JFormattedTextField NewVehicleOfInterestOwnerNameText;
    private javax.swing.JFormattedTextField NewVehicleOfInterestOwnerPhoneText;
    private javax.swing.JFormattedTextField NewVehicleOfInterestPlateText;
    private javax.swing.JFormattedTextField NewVehicleOfInterestReasonText;
    private javax.swing.JFormattedTextField NewVehicleOfInterestYearText;
    private javax.swing.JTextField ReasonForInterestDescriptionText;
    private javax.swing.JTextField ReasonForInterestText;
    private javax.swing.JPanel ReasonsForInterestPane;
    private javax.swing.JButton RemoveMakeButton;
    private javax.swing.JButton RemoveModelButton;
    private javax.swing.JButton RemoveReasonForInterestButton;
    private javax.swing.JButton RemoveVehicleOfInterestButton;
    private javax.swing.JButton ShowReasonsForInterestButton;
    private javax.swing.JButton ShowVehicleModelsButton;
    private javax.swing.JButton ShowVehiclesOfInterestButton;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JPanel VehicleModelsPane;
    private javax.swing.JButton VehiclesOfInterestLicenseSearchButton;
    private javax.swing.JPanel VehiclesOfInterestPane;
    private javax.swing.JTextField VehiclesOfInterestSearchText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
